(() => {
  'use strict';
  const F=window.FH,S=F.state,$=id=>document.getElementById(id);
  const el={app:$('app'),board:$('board'),overlay:$('boardOverlay'),banner:$('featureBanner'),msg:$('message'),mode:$('modeLabel'),profile:$('profileLabel'),last:$('lastWin'),cascade:$('cascadeLabel'),alarm:$('alarmRail'),credits:$('credits'),bet:$('bet'),spin:$('spinBtn'),spinSub:$('spinSub'),down:$('betDown'),up:$('betUp'),bonusMeter:$('bonusMeter'),bonusName:$('bonusName'),bonusSpins:$('bonusSpins'),meterFill:$('meterFill'),statSpins:$('statSpins'),statWagered:$('statWagered'),statWon:$('statWon'),statRtp:$('statRtp')};
  const allCells=()=>[...Array(F.CELLS).keys()];
  function msg(t,hot=false){el.msg.textContent=t;el.msg.classList.toggle('hot',hot);}
  function banner(t){el.banner.textContent=t;el.banner.classList.remove('show');void el.banner.offsetWidth;el.banner.classList.add('show');}
  function alarmRail(n){[...el.alarm.querySelectorAll('.alarm-dots i')].forEach((x,i)=>x.classList.toggle('active',i<n));}
  function tile(sym,i){const fire=S.fires[i],s=F.SYMBOLS[sym]||F.SYMBOLS.gloves,cls=['cell',sym==='wild'?'is-wild':'',sym==='alarm'?'is-alarm':'',sym==='firestarter'?'is-firestarter':''].filter(Boolean).join(' ');return `<div class="${cls}" data-i="${i}" role="gridcell" aria-label="${s.label}${fire?`, fire multiplier ${fire}x`:''}">${fire?'<span class="fire-layer"></span>':''}<span class="symbol">${s.icon}</span><span class="symbol-label">${s.label}</span>${fire?`<span class="fire-mult">×${fire}</span>`:''}</div>`;}
  function render(spawned=[],animate=false){el.board.innerHTML=S.board.map(tile).join('');if(animate)spawned.forEach(i=>el.board.querySelector(`[data-i="${i}"]`)?.classList.add('drop'));alarmRail(F.alarmCount(S.board));}
  async function winFx(wins){const ids=new Set(wins.flatMap(w=>w.positions));ids.forEach(i=>el.board.querySelector(`[data-i="${i}"]`)?.classList.add('win'));await F.sleep(600);}
  async function removeFx(ids){ids.forEach(i=>el.board.querySelector(`[data-i="${i}"]`)?.classList.add('pop'));await F.sleep(320);}
  async function featureFx(label,type){banner(label);el.overlay.innerHTML='';const n=document.createElement('div');n.className=`fx-${type}`;if(type==='truck')n.textContent='🚒';if(type==='axe')n.textContent='🪓';el.overlay.append(n);if(['axe','backdraft'].includes(type))el.app.classList.add('screen-shake');await F.sleep(900);el.overlay.innerHTML='';el.app.classList.remove('screen-shake');}
  async function feature(name,profile,t){
    if(name==='firetruck'){await featureFx('🚒 FIRETRUCK','truck');let n=F.randInt(2,5),c=allCells().filter(i=>S.board[i]!=='alarm'),p=[];while(n--&&c.length){const i=c.splice(Math.floor(F.rng()*c.length),1)[0];S.board[i]='wild';p.push(i);}t.featureData.firetruck=p;render([],true);await F.sleep(280);}
    if(name==='axe'){await featureFx('🪓 FIRE AXE','axe');let c=S.board.map((s,i)=>F.LOWS.has(s)?i:-1).filter(i=>i>=0),n=Math.min(c.length,F.randInt(3,6)),cut=[];while(n--&&c.length)cut.push(c.splice(Math.floor(F.rng()*c.length),1)[0]);t.featureData.axe=cut;await removeFx(cut);const r=F.cascadeBoard(S.board,cut,profile,{allowAlarm:false,allowFirestarter:t.features.includes('backdraft')});S.board=r.board;render(r.spawned,true);await F.sleep(280);}
    if(name==='hose'){await featureFx('💦 HOSE BLAST','hose');const row=F.randInt(0,F.ROWS-1),cut=Array.from({length:F.COLS},(_,c)=>row*F.COLS+c);t.featureData.hose={row,positions:cut};await removeFx(cut);const r=F.cascadeBoard(S.board,cut,profile,{allowAlarm:false,allowFirestarter:t.features.includes('backdraft')});S.board=r.board;render(r.spawned,true);await F.sleep(280);}
    if(name==='backdraft'){await featureFx('🔥 BACKDRAFT','backdraft');let n=F.randInt(3,5),a=allCells(),lit=[];while(n--&&a.length){const i=a.splice(Math.floor(F.rng()*a.length),1)[0];F.ignite(i);lit.push(i);}t.featureData.backdraft=lit;render([],true);await F.sleep(280);}
  }
  async function cascades(profile,t,{allowFirestarter=false}={}){let total=0,n=0;while(n<30){const starters=F.resolveFirestarters(S.board,profile,0);if(starters.length){t.firestarters.push(...starters);banner('🔥 FIRESTARTER');render([],true);await F.sleep(220);}const ev=F.evaluate(S.board,S.fires,profile);if(!ev.wins.length)break;n++;el.cascade.textContent=String(n);await winFx(ev.wins);total+=ev.total;msg(`CASCADE ${n} · +${ev.total.toFixed(2)}×`,true);ev.wins.forEach(w=>w.burning.forEach(F.upgradeFire));const spread=F.spreadFire(ev.wins.flatMap(w=>w.burning));t.cascades.push({n,wins:ev.wins.map(w=>({symbol:w.sym,count:w.count,base:+w.base.toFixed(4),fireMultiplier:w.fireMult,amount:+w.amount.toFixed(4)})),removed:ev.remove,spread});await removeFx(ev.remove);const r=F.cascadeBoard(S.board,ev.remove,profile,{allowAlarm:false,allowFirestarter});S.board=r.board;render(r.spawned,true);await F.sleep(360);}if(n>=30)t.guard='cascade safety cap reached';return total;}
  function startBonus(tier){const total=tier===3?8:tier===4?10:12;S.bonus={tier,total,remaining:total,won:0,persistent:tier===5};if(!S.bonus.persistent)S.fires.fill(0);banner(`${tier}-ALARM FIRE`);msg(`${total} FREE SPINS — ${tier===5?'FIRE PERSISTS':'FIRE RESETS EACH SPIN'}`,true);ui();}
  async function playBonus(profile,t){while(S.bonus&&S.bonus.remaining>0){if(!S.bonus.persistent)S.fires.fill(0);S.bonus.remaining--;ui();S.board=F.makeBoard(profile,{allowAlarm:false,allowFirestarter:true});render(allCells(),true);await F.sleep(360);const starters=F.resolveFirestarters(S.board,profile,0);if(starters.length){t.firestarters.push(...starters);banner('🔥 FIRESTARTER');render([],true);await F.sleep(220);}const w=await cascades(profile,t,{allowFirestarter:true});S.bonus.won+=w;t.bonusSpins.push({remaining:S.bonus.remaining,winX:+w.toFixed(4),fires:[...S.fires]});if(S.bonus.remaining)await F.sleep(350);}const x=S.bonus.won,tier=S.bonus.tier;banner(`${tier}-ALARM COMPLETE · ${x.toFixed(2)}×`);await F.sleep(900);S.bonus=null;S.fires.fill(0);return x;}
  function ui(){const bet=F.BETS[S.betIndex];el.credits.textContent=S.credits.toFixed(2);el.bet.textContent=bet.toFixed(2);el.spinSub.textContent=`$${bet.toFixed(2)}`;el.spin.disabled=S.busy||!!S.bonus;el.down.disabled=S.busy;el.up.disabled=S.busy;el.profile.textContent=`${S.currentProfile.target.toFixed(1)}%`;el.mode.textContent=S.bonus?`${S.bonus.tier}-ALARM BONUS`:'BASE GAME';el.statSpins.textContent=S.stats.spins;el.statWagered.textContent=S.stats.wagered.toFixed(2);el.statWon.textContent=S.stats.won.toFixed(2);el.statRtp.textContent=S.stats.wagered?`${(100*S.stats.won/S.stats.wagered).toFixed(1)}%`:'—';if(S.bonus){el.bonusMeter.hidden=false;el.bonusName.textContent=`${S.bonus.tier}-ALARM FIRE`;el.bonusSpins.textContent=S.bonus.remaining;el.meterFill.style.width=`${100*S.bonus.remaining/S.bonus.total}%`;el.app.classList.add('bonus-heat');}else{el.bonusMeter.hidden=true;el.app.classList.remove('bonus-heat');}}
  async function spin(){if(S.busy||S.bonus)return;const bet=F.BETS[S.betIndex];if(S.credits<bet){msg('INSUFFICIENT CREDITS');return;}S.busy=true;ui();S.spinId++;S.stats.spins++;S.stats.wagered+=bet;S.credits-=bet;const forced=F.dev?.consume()||null,profile=F.PROFILES[forced?.rtp||F.DEFAULT_RTP];S.currentProfile=profile;const features=forced?forced.features:F.chooseFeature(profile);const t={spinId:S.spinId,devForced:!!forced,seedTag:forced?.seedTag||null,profile:profile.target,bet,features:[...features],featureData:{},forcedBonus:forced?.bonus||0,forcedFirestarters:forced?.firestarters||0,cascades:[],firestarters:[],bonusSpins:[],initialBoard:null,totalX:0};msg('DISPATCHING…');el.cascade.textContent='—';S.fires.fill(0);S.board=F.makeBoard(profile,{allowAlarm:true,allowFirestarter:features.includes('backdraft')});if(forced?.bonus)F.forceAlarmCount(S.board,forced.bonus,profile);if(forced?.firestarters){let a=allCells().filter(i=>S.board[i]!=='alarm'),n=forced.firestarters;while(n--&&a.length)S.board[a.splice(Math.floor(F.rng()*a.length),1)[0]]='firestarter';}t.initialBoard=[...S.board];const locked=forced?.bonus||Math.min(5,F.alarmCount(S.board));t.lockedAlarmTier=locked>=3?locked:0;render(allCells(),true);await F.sleep(520);for(const f of features)await feature(f,profile,t);const starters=F.resolveFirestarters(S.board,profile,forced?.firestarters||0);if(starters.length){t.firestarters.push(...starters);banner('🔥 FIRESTARTER');render([],true);await F.sleep(360);}let total=await cascades(profile,t,{allowFirestarter:features.includes('backdraft')});if(locked>=3){startBonus(Math.min(5,locked));await F.sleep(850);total+=await playBonus(profile,t);}const win=total*bet;S.credits+=win;S.stats.won+=win;t.totalX=+total.toFixed(4);t.winCredits=+win.toFixed(4);S.lastTelemetry=t;el.last.textContent=`${total.toFixed(2)}×`;msg(total?`TOTAL WIN ${total.toFixed(2)}×`:'NO WIN — READY');S.fires.fill(0);render();S.busy=false;if(forced)F.dev?.clear();ui();F.dev?.telemetry();}

  el.spin.addEventListener('click',spin);el.down.addEventListener('click',()=>{if(!S.busy){S.betIndex=Math.max(0,S.betIndex-1);ui();}});el.up.addEventListener('click',()=>{if(!S.busy){S.betIndex=Math.min(F.BETS.length-1,S.betIndex+1);ui();}});
  S.board=F.makeBoard(S.currentProfile,{allowAlarm:false});render();ui();F.game={spin,render,ui};
})();
